name: mirror2vercel-cdxy

on:
  push:
    branches:
     - main
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: ${{ secrets.VERCELCDXY_TARGET_URL }}
        target-username: ${{ secrets.VERCELCDXY_TARGET_USERNAME }}
        target-token: ${{ secrets.VERCELCDXY_TARGET_TOKEN }}
