import { Invoice } from "./columns";

export const data: Invoice[] = [
  {
    invoice_number: "2023-ABC-123456",
    date: "2023-11-03",
    due_date: "2023-11-17",
    bill_to: {
      company_name: "Tech Solutions Inc.",
      address: "123 Tech Street",
      city: "Innovate City",
      state: "Techsylvania",
      zip: "12345",
      country: "USA",
    },
    ship_to: {
      company_name: "Tech Solutions Inc.",
      address: "456 Solution Ave",
      city: "Progress Town",
      state: "Techsylvania",
      zip: "67890",
      country: "USA",
    },
    items: [
      {
        item_id: "CPU001",
        description: "Quad-core CPU 3.6 GHz",
        unit_price: 250.0,
        quantity: 2,
        subtotal: 500.0,
      },
      {
        item_id: "RAM002",
        description: "16GB DDR4 RAM",
        unit_price: 90.0,
        quantity: 4,
        subtotal: 360.0,
      },
      {
        item_id: "HDD003",
        description: "1TB SSD Hard Drive",
        unit_price: 150.0,
        quantity: 1,
        subtotal: 150.0,
      },
      {
        item_id: "GPU004",
        description: "Gaming Graphics Card",
        unit_price: 400.0,
        quantity: 1,
        subtotal: 400.0,
      },
      {
        item_id: "PSU005",
        description: "750W Power Supply Unit",
        unit_price: 80.0,
        quantity: 1,
        subtotal: 80.0,
      },
      {
        item_id: "CASE006",
        description: "Mid Tower Computer Case",
        unit_price: 120.0,
        quantity: 1,
        subtotal: 120.0,
      },
    ],
    subtotals: {
      items_total: 1610.0,
      tax_rate: 0.07,
      tax_amount: 112.7,
      shipping_fee: 25.0,
      discount: 0.0,
    },
    total_due: 1747.7,
    notes: "Thank you for your business!",
  },

  {
    invoice_number: "2024-XYZ-654321",
    date: "2024-06-05",
    due_date: "2024-06-19",
    bill_to: {
      company_name: "Innovate Technologies Ltd.",
      address: "789 Innovation Blvd",
      city: "Tech City",
      state: "Futuristan",
      zip: "54321",
      country: "USA",
    },
    ship_to: {
      company_name: "Innovate Technologies Ltd.",
      address: "101 Future Road",
      city: "Advance Town",
      state: "Futuristan",
      zip: "98765",
      country: "USA",
    },
    items: [
      {
        item_id: "MON001",
        description: "27-inch 4K Monitor",
        unit_price: 300.0,
        quantity: 3,
        subtotal: 900.0,
      },
      {
        item_id: "MOU002",
        description: "Wireless Mouse",
        unit_price: 50.0,
        quantity: 5,
        subtotal: 250.0,
      },
      {
        item_id: "KB003",
        description: "Mechanical Keyboard",
        unit_price: 100.0,
        quantity: 3,
        subtotal: 300.0,
      },
      {
        item_id: "HD004",
        description: "External Hard Drive 2TB",
        unit_price: 120.0,
        quantity: 2,
        subtotal: 240.0,
      },
      {
        item_id: "SP005",
        description: "Bluetooth Speaker",
        unit_price: 80.0,
        quantity: 2,
        subtotal: 160.0,
      },
      {
        item_id: "WD006",
        description: "USB-C Hub",
        unit_price: 60.0,
        quantity: 4,
        subtotal: 240.0,
      },
    ],
    subtotals: {
      items_total: 2090.0,
      tax_rate: 0.08,
      tax_amount: 167.2,
      shipping_fee: 30.0,
      discount: 50.0,
    },
    total_due: 2237.2,
    notes: "We appreciate your prompt payment!",
  },
];
