name: mirror2vercel-cdxy

on:
  push:
    branches:
     - main
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Sync
      run: |
        git config --global user.email "mihajlo.novakovic@codaxy.com"
        git config --global user.name "mihajlo-cdxy"
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.VERCELCDXY_KEY }}'
        git remote add upstream git@github.com:vercel-cdxy/consumer-demo-app-nextjs.git
        git fetch upstream
        git merge upstream/main --allow-unrelated-histories
        git push
