name: mirror2vercel-cdxy

on:
  push:
    branches:
     - main
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        TARGET_REPO="https://${{ secrets.VERCELCDXY_TARGET_TOKEN }}@github.com/${{ secrets.VERCELCDXY_TARGET_PATH }}"
        git remote add target $TARGET_REPO
        git push target +refs/heads/main:refs/heads/main --force
