name: mirror4vercel

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo sync vercel-cdxy/consumer-demo-app-nextjs -b ${{ github.ref_name }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.Vercel_TOKEN }}
