name: mirror4vercel

on:
  push:
    branches:
     - main
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Sync
      run: |
        git config --global user.email "${{ secrets.VERCELCDXY_EMAIL }}"
        git config --global user.name "${{ secrets.VERCELCDXY_USER }}"
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.VERCELCDXY_KEY }}'
        git remote add vercel "${{ secrets.VERCELCDXY_TARGET_PATH }}"
        git push vercel --force
